version: '3'

services:
  token.services:
    image: token.services
    build:
      context: .
      dockerfile: TokenService/Dockerfile
    ports:
    - 5000:80

  signalr.services:
    image: signalr.services
    build:
      context: .
      dockerfile: SignalR.Services/Dockerfile
    ports:
    - 5001:80


  mahasiswa.services:
    image: mahasiswa.services
    build:
      context: .
      dockerfile: Mahasiswa.Services/Dockerfile
    ports:
    - 5002:80


  kelas.services:
    image: kelas.services
    build:
      context: .
      dockerfile: KRS_Microservices/Dockerfile
    ports:
    - 5003:80

