version: '3'

services:
  mahasiswa.services:
    image: mahasiswa.services
    build:
      context: .
      dockerfile: Mahasiswa.Services/Dockerfile

  kelas.services:
    image: kelas.services
    build:
      context: .
      dockerfile: KRS_Microservices/Dockerfile


  signalr.services:
    image: signalr.services
    build:
      context: .
      dockerfile: SignalR.Services/Dockerfile


  authserver:
    image: authserver
    build:
      context: .
      dockerfile: AuthServer/Dockerfile

  gateway:
    image: gateway
    build:
      context: .
      dockerfile: Gateway.services/Dockerfile

